# ===============================
# BASE DE DATOS - BUILD
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3307/bd_sispro_build?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate construye/ajusta tablas
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.baseline-on-migrate=true