spring.application.name=mcsv-legacy
server.port=8025
spring.cloud.compatibility-verifier.enabled=false

# PERFIL ACTIVO
spring.profiles.active=prod

#PARA CAMBIAR ENTRE LOS PERFILES DE DESARROLLO
## DEV (default) CORRESPONDE A BD DE CONSTRUCCIONES
#--spring.profiles.active=dev
#
## PROD (simulado)
#--spring.profiles.active=prod

# CONFIG GLOBAL
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

spring.jackson.time-zone=America/Santiago

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JPA GENERAL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.jpa.properties.hibernate.format_sql=true

# INTEGRACION
integration.traductor.url=http://localhost:8021

# ===============================
# DOCS
# ===============================
# Swagger:
# http://localhost:8098/swagger-ui/index.html